import {StyleSheet} from 'react-native';
import {colors, fonts} from './../../../styles';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2A7394',
    justifyContent: 'center',
  },
  containerImagem: {
    backgroundColor: colors.WHITE,
    // backgroundColor: 'red',
    width: 160,
    height: 160,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  containerConexao: {
    width: '100%',
    flexDirection: 'row',
    marginLeft: '5%',
    marginVertical: 10,
  },
  barra: {
    width: 40,
    borderRadius: 10,
    height: 15,
    backgroundColor: '#CCCCCC',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  barraAtivo: {
    width: 40,
    borderRadius: 10,
    height: 15,
    backgroundColor: '#2A7394',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  bol: {
    width: 20,
    height: 20,
    borderRadius: 15,
    backgroundColor: '#F1F1F1',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  bolAtivo: {
    width: 20,
    height: 20,
    borderRadius: 15,
    backgroundColor: '#FEB415',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  containerImg: {
    width: '100%',
    // marginTop: '-30%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imagem: {
    height: 150,
    width: 150,
  },
  button: {
    width: '90%',
    marginLeft: '5%',
    height: 500,
    flexDirection: 'column',
    justifyContent: 'center',
    borderRadius: 15,
  },
  buttonFacebook: {
    backgroundColor: '#4267B2',
  },
  buttonGoogle: {
    backgroundColor: '#A52728',
  },
  buttonAccount: {
    backgroundColor: colors.WHITE,
  },
  textInput: {
    width: '100%',
    height: '100%',
    flexWrap: 'nowrap',
  },
  buttonText: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: fonts.TITLE,
    marginBottom: 15,
  },
  text: {
    marginLeft: '5%',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#606D7E',
  },
  textConexao: {
    marginLeft: 10,
    fontSize: 16,
    marginBottom: 10,
    color: '#757575',
  },
  input: {
    backgroundColor: colors.WHITE,
    width: '90%',
    marginLeft: '5%',
    borderRadius: 10,
    height: 55,
    borderWidth: 1,
    borderColor: '#606D7E',
  },
  containerEntrar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  containerErro: {
    backgroundColor: 'red',
    borderRadius: 5,
    width: '90%',
    height: 30,
    marginLeft: '5%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoEntrar: {
    width: '90%',
    borderRadius: 10,
    height: 55,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEB415',
  },
  textBotao: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2A7394',
  },
  desenvolvido: {
    color: colors.WHITE,
    fontSize: 12,
  },
  containerDev: {
    width: '100%',
    height: 100,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
